/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const T__1 = IDL.Variant({
  'biology' : IDL.Null,
  'socialStudies' : IDL.Null,
  'hindi' : IDL.Null,
  'politicalScience' : IDL.Null,
  'history' : IDL.Null,
  'geography' : IDL.Null,
  'economics' : IDL.Null,
  'chemistry' : IDL.Null,
  'mathematics' : IDL.Null,
  'physics' : IDL.Null,
  'english' : IDL.Null,
  'science' : IDL.Null,
  'computerScience' : IDL.Null,
});
export const T = IDL.Variant({
  'jee' : IDL.Null,
  'class1' : IDL.Null,
  'class2' : IDL.Null,
  'class3' : IDL.Null,
  'class4' : IDL.Null,
  'class5' : IDL.Null,
  'class6' : IDL.Null,
  'class7' : IDL.Null,
  'class8' : IDL.Null,
  'class9' : IDL.Null,
  'neet' : IDL.Null,
  'class10' : IDL.Null,
  'class11' : IDL.Null,
  'class12' : IDL.Null,
});
export const DoubtQuestion = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'subject' : T__1,
  'teacher' : IDL.Text,
  'response' : IDL.Text,
  'student' : IDL.Principal,
  'classLevel' : T,
});
export const TeacherProfile = IDL.Record({
  'subjects' : IDL.Vec(T__1),
  'name' : IDL.Text,
  'classes' : IDL.Vec(T),
  'gender' : IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null }),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDoubtById' : IDL.Func([IDL.Nat], [IDL.Opt(DoubtQuestion)], ['query']),
  'getDoubtHistory' : IDL.Func([], [IDL.Vec(DoubtQuestion)], ['query']),
  'getDoubtHistoryBySubject' : IDL.Func(
      [T__1],
      [IDL.Vec(DoubtQuestion)],
      ['query'],
    ),
  'getDoubtHistoryByTeacher' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DoubtQuestion)],
      ['query'],
    ),
  'getDoubtsByStudent' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DoubtQuestion)],
      ['query'],
    ),
  'getLessonContent' : IDL.Func([T, T__1], [IDL.Opt(IDL.Text)], ['query']),
  'getMyDoubtHistory' : IDL.Func([], [IDL.Vec(DoubtQuestion)], ['query']),
  'getTeacherClasses' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(T))], ['query']),
  'getTeacherProfiles' : IDL.Func([], [IDL.Vec(TeacherProfile)], ['query']),
  'getTeacherSubjects' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(T__1))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSystem' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDoubtResponse' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'submitDoubt' : IDL.Func([IDL.Text, IDL.Text, T, T__1], [DoubtQuestion], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const T__1 = IDL.Variant({
    'biology' : IDL.Null,
    'socialStudies' : IDL.Null,
    'hindi' : IDL.Null,
    'politicalScience' : IDL.Null,
    'history' : IDL.Null,
    'geography' : IDL.Null,
    'economics' : IDL.Null,
    'chemistry' : IDL.Null,
    'mathematics' : IDL.Null,
    'physics' : IDL.Null,
    'english' : IDL.Null,
    'science' : IDL.Null,
    'computerScience' : IDL.Null,
  });
  const T = IDL.Variant({
    'jee' : IDL.Null,
    'class1' : IDL.Null,
    'class2' : IDL.Null,
    'class3' : IDL.Null,
    'class4' : IDL.Null,
    'class5' : IDL.Null,
    'class6' : IDL.Null,
    'class7' : IDL.Null,
    'class8' : IDL.Null,
    'class9' : IDL.Null,
    'neet' : IDL.Null,
    'class10' : IDL.Null,
    'class11' : IDL.Null,
    'class12' : IDL.Null,
  });
  const DoubtQuestion = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'subject' : T__1,
    'teacher' : IDL.Text,
    'response' : IDL.Text,
    'student' : IDL.Principal,
    'classLevel' : T,
  });
  const TeacherProfile = IDL.Record({
    'subjects' : IDL.Vec(T__1),
    'name' : IDL.Text,
    'classes' : IDL.Vec(T),
    'gender' : IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null }),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDoubtById' : IDL.Func([IDL.Nat], [IDL.Opt(DoubtQuestion)], ['query']),
    'getDoubtHistory' : IDL.Func([], [IDL.Vec(DoubtQuestion)], ['query']),
    'getDoubtHistoryBySubject' : IDL.Func(
        [T__1],
        [IDL.Vec(DoubtQuestion)],
        ['query'],
      ),
    'getDoubtHistoryByTeacher' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DoubtQuestion)],
        ['query'],
      ),
    'getDoubtsByStudent' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DoubtQuestion)],
        ['query'],
      ),
    'getLessonContent' : IDL.Func([T, T__1], [IDL.Opt(IDL.Text)], ['query']),
    'getMyDoubtHistory' : IDL.Func([], [IDL.Vec(DoubtQuestion)], ['query']),
    'getTeacherClasses' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(T))],
        ['query'],
      ),
    'getTeacherProfiles' : IDL.Func([], [IDL.Vec(TeacherProfile)], ['query']),
    'getTeacherSubjects' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(T__1))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSystem' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDoubtResponse' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'submitDoubt' : IDL.Func(
        [IDL.Text, IDL.Text, T, T__1],
        [DoubtQuestion],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };