/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DoubtQuestion {
  'id' : bigint,
  'question' : string,
  'subject' : T__1,
  'teacher' : string,
  'response' : string,
  'student' : Principal,
  'classLevel' : T,
}
export type T = { 'jee' : null } |
  { 'class1' : null } |
  { 'class2' : null } |
  { 'class3' : null } |
  { 'class4' : null } |
  { 'class5' : null } |
  { 'class6' : null } |
  { 'class7' : null } |
  { 'class8' : null } |
  { 'class9' : null } |
  { 'neet' : null } |
  { 'class10' : null } |
  { 'class11' : null } |
  { 'class12' : null };
export type T__1 = { 'biology' : null } |
  { 'socialStudies' : null } |
  { 'hindi' : null } |
  { 'politicalScience' : null } |
  { 'history' : null } |
  { 'geography' : null } |
  { 'economics' : null } |
  { 'chemistry' : null } |
  { 'mathematics' : null } |
  { 'physics' : null } |
  { 'english' : null } |
  { 'science' : null } |
  { 'computerScience' : null };
export interface TeacherProfile {
  'subjects' : Array<T__1>,
  'name' : string,
  'classes' : Array<T>,
  'gender' : { 'female' : null } |
    { 'male' : null },
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDoubtById' : ActorMethod<[bigint], [] | [DoubtQuestion]>,
  'getDoubtHistory' : ActorMethod<[], Array<DoubtQuestion>>,
  'getDoubtHistoryBySubject' : ActorMethod<[T__1], Array<DoubtQuestion>>,
  'getDoubtHistoryByTeacher' : ActorMethod<[string], Array<DoubtQuestion>>,
  'getDoubtsByStudent' : ActorMethod<[Principal], Array<DoubtQuestion>>,
  'getLessonContent' : ActorMethod<[T, T__1], [] | [string]>,
  'getMyDoubtHistory' : ActorMethod<[], Array<DoubtQuestion>>,
  'getTeacherClasses' : ActorMethod<[string], [] | [Array<T>]>,
  'getTeacherProfiles' : ActorMethod<[], Array<TeacherProfile>>,
  'getTeacherSubjects' : ActorMethod<[string], [] | [Array<T__1>]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSystem' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDoubtResponse' : ActorMethod<[bigint, string], undefined>,
  'submitDoubt' : ActorMethod<[string, string, T, T__1], DoubtQuestion>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];