/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DoubtQuestion {
    id: bigint;
    question: string;
    subject: T__1;
    teacher: string;
    response: string;
    student: Principal;
    classLevel: T;
}
export interface UserProfile {
    name: string;
    email: string;
}
export interface TeacherProfile {
    subjects: Array<T__1>;
    name: string;
    classes: Array<T>;
    gender: Variant_female_male;
}
export enum T {
    jee = "jee",
    class1 = "class1",
    class2 = "class2",
    class3 = "class3",
    class4 = "class4",
    class5 = "class5",
    class6 = "class6",
    class7 = "class7",
    class8 = "class8",
    class9 = "class9",
    neet = "neet",
    class10 = "class10",
    class11 = "class11",
    class12 = "class12"
}
export enum T__1 {
    biology = "biology",
    socialStudies = "socialStudies",
    hindi = "hindi",
    politicalScience = "politicalScience",
    history = "history",
    geography = "geography",
    economics = "economics",
    chemistry = "chemistry",
    mathematics = "mathematics",
    physics = "physics",
    english = "english",
    science = "science",
    computerScience = "computerScience"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_female_male {
    female = "female",
    male = "male"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDoubtById(doubtId: bigint): Promise<DoubtQuestion | null>;
    getDoubtHistory(): Promise<Array<DoubtQuestion>>;
    getDoubtHistoryBySubject(subject: T__1): Promise<Array<DoubtQuestion>>;
    getDoubtHistoryByTeacher(teacher: string): Promise<Array<DoubtQuestion>>;
    getDoubtsByStudent(studentId: Principal): Promise<Array<DoubtQuestion>>;
    getLessonContent(classLevel: T, subject: T__1): Promise<string | null>;
    getMyDoubtHistory(): Promise<Array<DoubtQuestion>>;
    getTeacherClasses(teacher: string): Promise<Array<T> | null>;
    getTeacherProfiles(): Promise<Array<TeacherProfile>>;
    getTeacherSubjects(teacher: string): Promise<Array<T__1> | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeSystem(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setDoubtResponse(doubtId: bigint, response: string): Promise<void>;
    submitDoubt(question: string, teacherName: string, classLevel: T, subject: T__1): Promise<DoubtQuestion>;
}
import type { DoubtQuestion as _DoubtQuestion, T as _T, T__1 as _T__1, TeacherProfile as _TeacherProfile, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoubtById(arg0: bigint): Promise<DoubtQuestion | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoubtById(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoubtById(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoubtHistory(): Promise<Array<DoubtQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoubtHistory();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoubtHistory();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoubtHistoryBySubject(arg0: T__1): Promise<Array<DoubtQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoubtHistoryBySubject(to_candid_T__1_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoubtHistoryBySubject(to_candid_T__1_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoubtHistoryByTeacher(arg0: string): Promise<Array<DoubtQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoubtHistoryByTeacher(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoubtHistoryByTeacher(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoubtsByStudent(arg0: Principal): Promise<Array<DoubtQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoubtsByStudent(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoubtsByStudent(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLessonContent(arg0: T, arg1: T__1): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonContent(to_candid_T_n16(this._uploadFile, this._downloadFile, arg0), to_candid_T__1_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonContent(to_candid_T_n16(this._uploadFile, this._downloadFile, arg0), to_candid_T__1_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDoubtHistory(): Promise<Array<DoubtQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDoubtHistory();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDoubtHistory();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacherClasses(arg0: string): Promise<Array<T> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherClasses(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherClasses(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacherProfiles(): Promise<Array<TeacherProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherProfiles();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherProfiles();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacherSubjects(arg0: string): Promise<Array<T__1> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherSubjects(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherSubjects(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeSystem(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeSystem();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeSystem();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setDoubtResponse(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDoubtResponse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDoubtResponse(arg0, arg1);
            return result;
        }
    }
    async submitDoubt(arg0: string, arg1: string, arg2: T, arg3: T__1): Promise<DoubtQuestion> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDoubt(arg0, arg1, to_candid_T_n16(this._uploadFile, this._downloadFile, arg2), to_candid_T__1_n14(this._uploadFile, this._downloadFile, arg3));
                return from_candid_DoubtQuestion_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDoubt(arg0, arg1, to_candid_T_n16(this._uploadFile, this._downloadFile, arg2), to_candid_T__1_n14(this._uploadFile, this._downloadFile, arg3));
            return from_candid_DoubtQuestion_n7(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DoubtQuestion_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DoubtQuestion): DoubtQuestion {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_T__1_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__1): T__1 {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_T_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TeacherProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeacherProfile): TeacherProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_T>]): Array<T> | null {
    return value.length === 0 ? null : from_candid_vec_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_T__1>]): Array<T__1> | null {
    return value.length === 0 ? null : from_candid_vec_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DoubtQuestion]): DoubtQuestion | null {
    return value.length === 0 ? null : from_candid_DoubtQuestion_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subjects: Array<_T__1>;
    name: string;
    classes: Array<_T>;
    gender: {
        female: null;
    } | {
        male: null;
    };
}): {
    subjects: Array<T__1>;
    name: string;
    classes: Array<T>;
    gender: Variant_female_male;
} {
    return {
        subjects: from_candid_vec_n24(_uploadFile, _downloadFile, value.subjects),
        name: value.name,
        classes: from_candid_vec_n20(_uploadFile, _downloadFile, value.classes),
        gender: from_candid_variant_n25(_uploadFile, _downloadFile, value.gender)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    question: string;
    subject: _T__1;
    teacher: string;
    response: string;
    student: Principal;
    classLevel: _T;
}): {
    id: bigint;
    question: string;
    subject: T__1;
    teacher: string;
    response: string;
    student: Principal;
    classLevel: T;
} {
    return {
        id: value.id,
        question: value.question,
        subject: from_candid_T__1_n9(_uploadFile, _downloadFile, value.subject),
        teacher: value.teacher,
        response: value.response,
        student: value.student,
        classLevel: from_candid_T_n11(_uploadFile, _downloadFile, value.classLevel)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    biology: null;
} | {
    socialStudies: null;
} | {
    hindi: null;
} | {
    politicalScience: null;
} | {
    history: null;
} | {
    geography: null;
} | {
    economics: null;
} | {
    chemistry: null;
} | {
    mathematics: null;
} | {
    physics: null;
} | {
    english: null;
} | {
    science: null;
} | {
    computerScience: null;
}): T__1 {
    return "biology" in value ? T__1.biology : "socialStudies" in value ? T__1.socialStudies : "hindi" in value ? T__1.hindi : "politicalScience" in value ? T__1.politicalScience : "history" in value ? T__1.history : "geography" in value ? T__1.geography : "economics" in value ? T__1.economics : "chemistry" in value ? T__1.chemistry : "mathematics" in value ? T__1.mathematics : "physics" in value ? T__1.physics : "english" in value ? T__1.english : "science" in value ? T__1.science : "computerScience" in value ? T__1.computerScience : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jee: null;
} | {
    class1: null;
} | {
    class2: null;
} | {
    class3: null;
} | {
    class4: null;
} | {
    class5: null;
} | {
    class6: null;
} | {
    class7: null;
} | {
    class8: null;
} | {
    class9: null;
} | {
    neet: null;
} | {
    class10: null;
} | {
    class11: null;
} | {
    class12: null;
}): T {
    return "jee" in value ? T.jee : "class1" in value ? T.class1 : "class2" in value ? T.class2 : "class3" in value ? T.class3 : "class4" in value ? T.class4 : "class5" in value ? T.class5 : "class6" in value ? T.class6 : "class7" in value ? T.class7 : "class8" in value ? T.class8 : "class9" in value ? T.class9 : "neet" in value ? T.neet : "class10" in value ? T.class10 : "class11" in value ? T.class11 : "class12" in value ? T.class12 : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
}): Variant_female_male {
    return "female" in value ? Variant_female_male.female : "male" in value ? Variant_female_male.male : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DoubtQuestion>): Array<DoubtQuestion> {
    return value.map((x)=>from_candid_DoubtQuestion_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T>): Array<T> {
    return value.map((x)=>from_candid_T_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeacherProfile>): Array<TeacherProfile> {
    return value.map((x)=>from_candid_TeacherProfile_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__1>): Array<T__1> {
    return value.map((x)=>from_candid_T__1_n9(_uploadFile, _downloadFile, x));
}
function to_candid_T__1_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T__1): _T__1 {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_T_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): _T {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T__1): {
    biology: null;
} | {
    socialStudies: null;
} | {
    hindi: null;
} | {
    politicalScience: null;
} | {
    history: null;
} | {
    geography: null;
} | {
    economics: null;
} | {
    chemistry: null;
} | {
    mathematics: null;
} | {
    physics: null;
} | {
    english: null;
} | {
    science: null;
} | {
    computerScience: null;
} {
    return value == T__1.biology ? {
        biology: null
    } : value == T__1.socialStudies ? {
        socialStudies: null
    } : value == T__1.hindi ? {
        hindi: null
    } : value == T__1.politicalScience ? {
        politicalScience: null
    } : value == T__1.history ? {
        history: null
    } : value == T__1.geography ? {
        geography: null
    } : value == T__1.economics ? {
        economics: null
    } : value == T__1.chemistry ? {
        chemistry: null
    } : value == T__1.mathematics ? {
        mathematics: null
    } : value == T__1.physics ? {
        physics: null
    } : value == T__1.english ? {
        english: null
    } : value == T__1.science ? {
        science: null
    } : value == T__1.computerScience ? {
        computerScience: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): {
    jee: null;
} | {
    class1: null;
} | {
    class2: null;
} | {
    class3: null;
} | {
    class4: null;
} | {
    class5: null;
} | {
    class6: null;
} | {
    class7: null;
} | {
    class8: null;
} | {
    class9: null;
} | {
    neet: null;
} | {
    class10: null;
} | {
    class11: null;
} | {
    class12: null;
} {
    return value == T.jee ? {
        jee: null
    } : value == T.class1 ? {
        class1: null
    } : value == T.class2 ? {
        class2: null
    } : value == T.class3 ? {
        class3: null
    } : value == T.class4 ? {
        class4: null
    } : value == T.class5 ? {
        class5: null
    } : value == T.class6 ? {
        class6: null
    } : value == T.class7 ? {
        class7: null
    } : value == T.class8 ? {
        class8: null
    } : value == T.class9 ? {
        class9: null
    } : value == T.neet ? {
        neet: null
    } : value == T.class10 ? {
        class10: null
    } : value == T.class11 ? {
        class11: null
    } : value == T.class12 ? {
        class12: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
